[package]
name = "gentlemen"
version = "0.1.0"
edition = "2024"

[dependencies]
async-openai = { version = "0.28.3" }
tokio = { version = "1.45.1" }
serde_json = { version = "1.0.140" }
serde = { version = "1.0.219" }
regex = { version = "1.11.1" }
